import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

import Bio from '../components/Bio';
import Post from '../components/Post';
import PostForm from '../components/PostForm';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Bio
          headshot='https://res.cloudinary.com/hackit-africa/image/upload/c_thumb,w_200,g_face/v1580219806/me.jpg'
          name='Eugene Musebe'
          tagline='Community Builder!'
          role='Developer Advocate @ Cloudinary'
        />
        {/* <h1 className={styles.title}>My Posts</h1> */}{' '}
      
        <ul className={styles.posts}>
          <li>
            <Post content='Hello, world!' date='2020-01-01' />
          </li>

          <li>
            <Post
              content='I’m working in Figma trying to design a new website that shows all
              of my tweets!'
            />
          </li>

          <li>
            <Post
              content='I’m working in Figma trying to design a new website that shows all
              of my tweets!'
              date='5/09/2022'
            />
          </li>
        </ul>
        <PostForm />
      </main>
    </div>
  );
}
